
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author usuario 1
 */
public class Telaprincipal extends javax.swing.JFrame {

    /**
     * Creates new form Telaprincipal
     */
    public Telaprincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtEntrar = new javax.swing.JButton();
        txtSair = new javax.swing.JButton();
        txtSenha = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela de Login");
        setBackground(new java.awt.Color(204, 255, 204));
        setMinimumSize(new java.awt.Dimension(500, 380));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Cadastro de Clientes");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 40, 233, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 204));
        jLabel2.setText("Usuário");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(178, 119, 60, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 204));
        jLabel3.setText("Senha");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(178, 159, 50, 20);
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(249, 116, 90, 22);

        txtEntrar.setBackground(new java.awt.Color(255, 255, 204));
        txtEntrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtEntrar.setForeground(new java.awt.Color(51, 0, 204));
        txtEntrar.setText("Entrar");
        txtEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(txtEntrar);
        txtEntrar.setBounds(112, 249, 72, 27);

        txtSair.setBackground(new java.awt.Color(255, 255, 204));
        txtSair.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtSair.setForeground(new java.awt.Color(51, 0, 204));
        txtSair.setText("Sair");
        txtSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSairActionPerformed(evt);
            }
        });
        getContentPane().add(txtSair);
        txtSair.setBounds(310, 249, 72, 27);
        getContentPane().add(txtSenha);
        txtSenha.setBounds(250, 160, 64, 22);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/imagem01.jpeg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 20, 420, 290);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEntrarActionPerformed
        /*String username = txtusuario.getText().toLowerCase(); // Converter para letras minúsculas
        String password = new String(txtsenha.getPassword());
        if (username.equals("ediberto") && password.equals("123")) {
            JOptionPane.showMessageDialog(null, "Usuário logado no sistema");
        } else {
            JOptionPane.showMessageDialog(null, "Usuário e/ou senha inválidos");
        } */    
       //OU ASSIM

       if(txtUsuario.getText().equals("ediberto") && new String(txtSenha.getPassword()).equals("123")){
            JOptionPane.showMessageDialog(null, "Usuário logado no sistema");
            //ABRE A TELA CADCLIENTES
            CadClientes cadclientes = new CadClientes();
            cadclientes.setVisible(true);
            //FECHAR A TELAPRINCIPAL
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Usuário e/ou senha inválidos");
        } 
 

    }//GEN-LAST:event_txtEntrarActionPerformed

    private void txtSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSairActionPerformed
         // SAIR DO SISTEMA
        this.dispose(); // Fecha a janela atual
        JOptionPane.showMessageDialog(null, "SISTEMA FECHADO!!!");

    }//GEN-LAST:event_txtSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Telaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Telaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Telaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Telaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Telaprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton txtEntrar;
    private javax.swing.JButton txtSair;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
