/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Teladelogin;

import javax.swing.JOptionPane;

/**
 *
 * @author usuario 1
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtusuario = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtBotaoEntrar = new javax.swing.JButton();
        txtBotaoSair = new javax.swing.JButton();
        txtsenha = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela de Login");
        setBackground(new java.awt.Color(204, 255, 204));
        setMinimumSize(new java.awt.Dimension(500, 300));
        getContentPane().setLayout(null);

        jLabel2.setBackground(new java.awt.Color(204, 255, 204));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Cadastro de Clientes");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 0, 240, 40);

        txtusuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtusuario);
        txtusuario.setBounds(230, 70, 90, 26);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Usuário");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 70, 60, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Senha");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(170, 110, 50, 20);

        txtBotaoEntrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtBotaoEntrar.setForeground(new java.awt.Color(0, 102, 102));
        txtBotaoEntrar.setText("Entrar");
        txtBotaoEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBotaoEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(txtBotaoEntrar);
        txtBotaoEntrar.setBounds(140, 210, 72, 27);

        txtBotaoSair.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtBotaoSair.setForeground(new java.awt.Color(0, 102, 102));
        txtBotaoSair.setText("Sair");
        txtBotaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBotaoSairActionPerformed(evt);
            }
        });
        getContentPane().add(txtBotaoSair);
        txtBotaoSair.setBounds(280, 210, 72, 27);
        getContentPane().add(txtsenha);
        txtsenha.setBounds(230, 110, 90, 22);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/imagem01.jpeg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 40, 350, 200);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtBotaoEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBotaoEntrarActionPerformed
        // EVENTO ONCLICK DO BOTÃO ENTRAR
      /*String username = txtusuario.getText().toLowerCase(); // Converter para letras minúsculas
        String password = new String(txtsenha.getPassword());
        if (username.equals("ediberto") && password.equals("123")) {
            JOptionPane.showMessageDialog(null, "Usuário logado no sistema");
        } else {
            JOptionPane.showMessageDialog(null, "Usuário e/ou senha inválidos");
        } */    
       //OU ASSIM

       if(txtusuario.getText().equals("ediberto") && new String(txtsenha.getPassword()).equals("123")){
            JOptionPane.showMessageDialog(null, "Usuário logado no sistema");
        } else {
            JOptionPane.showMessageDialog(null, "Usuário e/ou senha inválidos");
        } 
    }//GEN-LAST:event_txtBotaoEntrarActionPerformed

    private void txtBotaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBotaoSairActionPerformed
        // SAIR DO SISTEMA
        this.dispose(); // Fecha a janela atual
        JOptionPane.showMessageDialog(null, "SISTEMA FECHADO!!!");
    }//GEN-LAST:event_txtBotaoSairActionPerformed

    private void txtusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton txtBotaoEntrar;
    private javax.swing.JButton txtBotaoSair;
    private javax.swing.JPasswordField txtsenha;
    private javax.swing.JFormattedTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
